baseurl: /
canonifyURLs: false
disableAliases: true
disableHugoGeneratorInject: true
enableEmoji: true
enableGitInfo: false
enableRobotsTXT: true
paginate: 7
rssLimit: 10

# i18n
defaultContentLanguage: en
defaultContentLanguageInSubdir: false

# add redirects/headers
outputs:
  home:
    - HTML
    - RSS
  section:
    - HTML
    - RSS
    - SITEMAP

# add output format for section sitemap.xml
outputFormats:
  SITEMAP:
    mediaType: application/xml
    baseName: sitemap
    isHTML: false
    isPlainText: true
    noUgly: true
    rel: sitemap

markup:
  goldmark:
    extensions:
      linkify: false
    parser:
      autoHeadingID: true
      autoHeadingIDType: github
      attribute:
        block: true
        title: true
    renderer:
      unsafe: true
  highlight:
    codeFences: false
    guessSyntax: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: dracula
    tabWidth: 4

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

taxonomies:
  contributor: contributors

RelPermalinks:
  blog: '/blog/:title/'

module:
  mounts:
    - source: assets
      target: assets
    - source: static
      target: static
    - source: node_modules/flexsearch
      target: assets/js/vendor/flexsearch
    - source: node_modules/katex
      target: assets/js/vendor/katex
