# i18n languages config
en:
  languageCode: en-us
  contentDir: content/en
  languageName: English
  weight: 10

zh-cn:
  languageCode: zh-cn
  contentDir: content/zh-cn
  languageName: 简体中文
  weight: 15
